apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: togglemaster/targeting-service
    newName: iad.ocir.io/idjtuagz9un0/togglemaster/targeting-service
    newTag: sha-15ca04f4d523

labels:
  - pairs:
      app.kubernetes.io/environment: homolog
